parameters:
  - name: displayName
    type: string

  - name: dependsOn
    type: object
    default: ''

  - name: subscription
    type: string

  - name: environment
    type: string

jobs:
- job: PreparePolicies
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ../steps/replace-token.yaml
    parameters:
      path: '**/*-policy.xml'
      environment: ${{ parameters.environment }}
  - template: ../steps/set-policies.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
  - template: ../steps/delete-endpoints.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
