parameters:
  - name: dependsOn
    type: object
    default: ''
  
  - name: displayName
    type: string

  - name: hostNameType
    type: string
    default: "Proxy"

jobs:
- job: ApplyHostName
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  steps:
  - bash: |
      pwsh -ExecutionPolicy Unrestricted -File "$(System.DefaultWorkingDirectory)/script/apply_custom_domain.ps1" -Hostname $(hostName) -HostnameType ${{ parameters.hostNameType }} -Environment $(environment) -Tenant $(tenant_id) -ServicePrincipalId $(sp_app_id) -ServicePrincipalSecret $(sp_secret) -SubscriptionId $(subscription_id)
