parameters:
  - name: dependsOn
    type: object
  
  - name: displayName
    type: string
  
  - name: hostName
    type: string
  
  - name: group
    type: string
  
  - name: hostNameType
    type: string
    default: "Proxy"

jobs:
- job: ApplyHostName
  variables:
  - group: ${{ parameters.group }}
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  steps:
  - bash: |
      pwsh -ExecutionPolicy Unrestricted -File "$(System.DefaultWorkingDirectory)/script/apply_custom_domain.ps1" -Hostname ${{ parameters.hostname }} -HostnameType ${{ parameters.hostNameType }} -Environment $(environment) -Tenant $(tenant_id) -ServicePrincipalId $(sp_id_sbox) -ServicePrincipalSecret $(sp_secret_sbox) -SubscriptionId $(subscription_id)