parameters:
  - name: subscription
    type: string

  - name: resourceGroup
    type: string

  - name: dependsOn
    type: object
  
  - name: displayName
    type: string

  - name: environment
    type: string
  
  - name: hostName
    type: string
  
  - name: hostNameType
    type: string
    default: "Proxy"

  - name: variables
    type: object

jobs:
- job: ApplyHostName
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - bash |
      PowerShell -ExecutionPolicy Unrestricted -File "$(System.DefaultWorkingDirectory)/script/apply_custom_domain.ps1" -Hostname ${{ parameters.hostname }} -HostnameType ${{ parameters.hostNameType }} -KeyVaultName "hmi-shared-kv-${{ parameters.environment }}" -ResourceGroupName $(resourceGroup)
