parameters:
  - name: subscription
    type: string

  - name: resourceGroup
    type: string

  - name: dependsOn
    type: object
  
  - name: displayName
    type: string

  - name: environment
    type: string
  
  - name: hostName
    type: string
  
  - name: hostNameType
    type: string
    default: "Proxy"

  - name: variables
    type: object

jobs:
- job: ApplyHostName
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        spid=$(az apim show -n hmi-apim-svc-${{ parameters.environment }} -g hmi-apim-${{ parameters.environment }}-rg --query "identity.principalId" -o tsv)
        az keyvault set-policy --name hmi-shared-kv-${{ parameters.environment }} --object-id $spid --secret-permissions get list

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      ScriptType: 'FilePath'
      ScriptPath: 'script/apply_custom_domain.ps1'
      ScriptArguments: '-Hostname ${{ parameters.hostname }} -HostnameType ${{ parameters.hostNameType }} -KeyVaultName "hmi-shared-kv-${{ parameters.environment }}" -ResourceGroupName $(resourceGroup)'
      azurePowerShellVersion: 'LatestVersion'


      