parameters:
  - name: subscription
    type: string

  - name: resourceGroup
    type: string

  - name: dependsOn
    type: object
  
  - name: displayName
    type: string

  - name: certificateUrl
    type: string
  
  - name: hostName
    type: string
  
  - name: hostNameType
    type: string
    default: "Proxy"

jobs:
- job: ApplyHostName
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      # ScriptType: 'FilePath'
      # ScriptPath: 'script/apply_custom_domain.ps1'
      # ScriptArguments: '-Hostname ${{ parameters.hostName }} -HostnameType ${{ parameters.hostNameType }} -KeyVaultId ${{ parameters.certificateUrl }} -ResourceGroupName ${{ parameters.resourceGroup }}'
      ScriptType: 'InlineScript'
      Inline: |
        Install-Module -Name Az.ApiManagement -Force
        $proxy = New-AzApiManagementCustomHostnameConfiguration -Hostname ${{ parameters.hostName }} -HostnameType ${{ parameters.hostNameType }} -KeyVaultId ${{ parameters.certificateUrl }} -DefaultSslBinding
        $apim = Get-AzApiManagement -ResourceGroupName $(resourceGroup)
        $apim.ProxyCustomHostnameConfiguration = $proxy
        Set-AzApiManagement -InputObject $apim -SystemAssignedIdentity
      azurePowerShellVersion: 'LatestVersion'


      