parameters:
  - name: subscription
    type: string

  - name: resourceGroup
    type: string

  - name: storageAccount
    type: string

  - name: dependsOn
    type: object
  
  - name: displayName
    type: string
  
  - name: variables
    type: object

jobs:
- job: createStorage
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - task: AzureCLI@2
    displayName: createContainer
    name: createContainer
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Obtaining storage key..."
        key=$(az storage account keys list -g $(resourceGroup) --account-name $(storageAccount) --query "[0].value" -o tsv)
        echo "Creating storage container"
        container="test-results-"$(date +"%m-%d-%y")
        az storage container create --name $container --account-name $(storageAccount) --account-key $key
        echo "##vso[task.setvariable variable=storagekey;isOutput=true;isSecret=true;]$key"
        echo "##vso[task.setvariable variable=container;isOutput=true;isSecret=true;]$container"
