parameters:
  - name: dependsOn
    type: object
    default: ''

  - name: displayName
    type: string
 
  - name: subscription
    type: string

  - name: environment
    type: string

jobs:
- job: CreateDtuLogicApp
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ../steps/replace-token.yaml
    parameters:
      path: '**/parameters-*.json'
      environment: ${{ parameters.environment }}
  - template: templates/Azure/Common/get-service-connection-details.yaml@azTemplates
    parameters:
      subscriptionName: ${{ parameters.subscription }}
  - task: replacetokens@3
    displayName: Replace variables in Logic App workflow JSON
    inputs:
      rootDirectory: $(Build.SourcesDirectory)
      targetFiles: '**/*-la.json'
      encoding: 'auto'
      escapeType: 'html'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
      useLegacyPattern: false
      enableTelemetry: true
  - task: AzureCLI@2
    displayName: Create DTU Logic App
    name: createLogicApp
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Install az logic CLI extension"
        az extension add --name logic
        echo "Creating DTU Logic Application for $(environment)"ooh
        resourceGroupName="hmi-sharedinfra-$(environment)-rg"
        az logic workflow create --name "hmi-la-dturota-$(environment)-test" --resource-group $resourceGroupName --location "uksouth" --definition "$(System.DefaultWorkingDirectory)\infrastructure\logic-app\rota\hmi-la-rota-dtu-la.json"
        echo "Creating DTU Logic Application - Sitting Patterns"
        az logic workflow create --name "hmi-la-sittingpattern-publisher-$(enviornment)-test" --resource-group $resourceGroupName --location "uksouth" --definition "$(System.DefaultWorkingDirectory)\infrastructure\logic-app\sitting-pattern\hmi-la-sittingpatteren-publisher-la.json"
        az logic workflow create --name "hmi-la-sittingpattern-retriever-$(enviornment)-test" --resource-group $resourceGroupName --location "uksouth" --definition "$(System.DefaultWorkingDirectory)\infrastructure\logic-app\sitting-pattern\hmi-la-sittingpatteren-retriever-la.json"
        echo "Creating DTU Logic Applications is complete"
  - task: AzureCLI@2
    displayName: Give Logic App Access to Key Vault
    name: kv_access
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $env="$(environment)"
        $workflowNames=@("hmi-la-dturota-$env", "hmi-la-listing-data-export-$env", "hmi-la-sittingpattern-publisher-$env", "hmi-la-sittingpattern-retriever-$env")
        $resourceGroupName="hmi-sharedinfra-$env-rg"
        $kv_name="hmi-shared-kv-$env"

        az config set extension.use_dynamic_install=yes_without_prompt

        foreach ($workflowName in $workflowNames){

            $workflowIdentity = az logic workflow list --resource-group "$resourceGroupName" --query "[? name=='$workflowName'].identity" --only-show-errors | ConvertFrom-Json

            if ($null -eq  $workflowIdentity.principalId -or "" -eq $workflowIdentity.principalId ){
                Write-Host "No Identities found in $workflowName."
            } else {
                Write-Host "$workflowName identities."
                Write-Host $( $workflowIdentity | ConvertTo-Json)

                Write-Host "Give Permissions to $kv_name"
                $sp_id=$workflowIdentity.principalId
                az keyvault set-policy --name $kv_name --object-id $sp_id --secret-permissions get list
            }
        }

        