parameters:
  - name: dependsOn
    type: object
    default: ''

  - name: displayName
    type: string
 
  - name: subscription
    type: string

jobs:
- job: CreateDtuLogicApp
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: ../steps/replace-token.yaml
    parameters:
      path: '**/parameters-*.json'
      environment: 'dev'
  - task: AzureCLI@2
    displayName: Create DTU Logic App
    name: createLogicApp
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Creating DTU Logic Application for $(environment)"
        resourceGroupName="hmi-sharedinfra-$(environment)-rg"
        az deployment group create --resource-group $resourceGroupName --template-file "$(System.DefaultWorkingDirectory)\infrastructure\logic-app\LogicAppDtu.json" --parameters "$(System.DefaultWorkingDirectory)\infrastructure\logic-app\parameters-$(environment).json"
        echo "Creating DTU Logic Application is complete"