parameters:
  - name: dependsOn
    type: object
    default: ''

  - name: displayName
    type: string
 
  - name: subscription
    type: string

jobs:
- job: CreateStorage
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzureCLI@2
    displayName: Create ROTA Storage for ${{ environment.name }}
    name: createContainer
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Creating ROTA storage account for ${{ environment.name }}"