parameters:
  - name: subscription
    type: string
  
  - name: resourceGroup
    type: string

jobs:
- job: deleteResources
  displayName: Delete Resources
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzureCLI@2
    displayName: Delete Resource Group
    name: deleteResourceGroup
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az group delete --resource-group ${{ parameters.resourceGroup }} --subscription ${{ parameters.subscription }} --yes