parameters:
  - name: subscription
    type: string
  
  - name: resourceGroup
    type: string
  
  - name: apim
    type: string

jobs:
- job: deleteAPIM
  displayName: Delete Resources
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzureCLI@2
    displayName: Delete Resource Group
    name: deleteAPIM
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
# az apim delete --name ${{ parameters.apim }} --resource-group ${{ parameters.resourceGroup }} --subscription ${{ parameters.subscription }} --yes
        deployments=$(az deployment group list --resource-group ${{ parameters.resourceGroup }} --query [].name -o tsv)
        echo $deployments
# for deployment in $deployments; do az deployment group delete --name $deployment --resource-group ${{ parameters.resourceGroup }} }; done