parameters:
  - name: subscription
    type: string
  
  - name: resourceGroup
    type: string
  
  - name: apim
    type: string

jobs:
- job: deleteAPIM
  displayName: Delete Resources
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzureCLI@2
    displayName: Delete Resource Group
    name: deleteAPIM
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az apim delete --name ${{ parameters.apim }} --resource-group ${{ parameters.resourceGroup }} --subscription ${{ parameters.subscription }} --yes