parameters:
  - name: subscription
    type: string
  
  - name: resourceGroup
    type: string
  
  - name: apim
    type: string

jobs:
- job: deleteAPIM
  displayName: Delete Resources
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: AzureCLI@2
    displayName: Delete Resource Group
    name: deleteAPIM
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az apim delete -n ${{ parameters.apim }} -g ${{ parameters.resourceGroup }} --subscription ${{ parameters.subscription }} --yes
        deployments=$(az deployment group list -g ${{ parameters.resourceGroup }} --query [].name -o tsv)
        for deployment in $deployments; do 
          echo az deployment group delete -g ${{ parameters.resourceGroup }} -n $deployment
          az deployment group delete -g ${{ parameters.resourceGroup }} -n $deployment
        ; done
      