parameters:
  - name: subscription
    type: string

  - name: keyVaultName
    type: string

  - name: dependsOn
    type: object
  
  - name: displayName
    type: string

  - name: group
    type: string

jobs:
- job: ExportKeyVault
  variables:
  - group: ${{ parameters.group }}
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Export Secrets from KeyVault'
    inputs:
      azureSubscription: ${{ variables.subscription }}
      keyVaultName: hmi-apim-kv-${{ variables.environment}}
      secretsFilter: 'hmi-apim-sub-key'
  - script: |
      echo "##vso[task.setvariable variable=hmi-apim-sub-key;isOutput=true;isSecret=true]$(hmi-apim-sub-key)"
    displayName: 'Export KeyVault Variables'
    name: exportKeyVaultSecret
