parameters:
  - name: dependsOn
    type: object
    default: ''

  - name: displayName
    type: string
 
  - name: subscription
    type: string

jobs:
- job: ExportKeyVault
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Export Secrets from KeyVault'
    inputs:
      azureSubscription: ${{ parameters.subscription }}
      keyVaultName: hmi-shared-kv-$(environment)
      secretsFilter: 'hmi-apim-sub-key'
  - script: |
      echo "##vso[task.setvariable variable=hmi-apim-sub-key;isOutput=true;isSecret=true]$(hmi-apim-sub-key)"
    displayName: 'Export KeyVault Variables'
    name: exportKeyVaultSecret
