parameters:
  - name: displayName
    type: string

  - name: dependsOn
    type: object

  - name: subscriptionKey
    type: string

  - name: apimHost
    type: string

  - name: command
    type: string

jobs:
- job: ${{ parameters.displayName }}
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'
    
  variables:
    subscriptionKey: $[ dependencies.ExportKeyVault.outputs['exportKeyVaultSecret.hmi-apim-sub-key'] ]
  steps:
   - template: ../steps/run-gradlew.yaml
     parameters:
       runCommand: ${{ parameters.command }} -DTEST_SUBSCRIPTION_KEY=$(subscriptionKey) -DTEST_URL=https://${{ parameters.apimHost }} -DTEST_HOST=${{ parameters.apimHost }}
