parameters:
  - name: displayName
    type: string
    default: ''

  - name: dependsOn
    type: object
    default: []

  - name: subscriptionKey
    type: string
    default: ''

  - name: apimHost
    type: string
    default: ''

  - name: command
    type: string
    default: ''


jobs:
  - job: GradleTest
    dependsOn: 
    - ${{ if parameters.dependsOn }}:
      - ${{ parameters.dependsOn }}
    displayName: Functional Test
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo ${{ parameters.command }} -DTEST_SUBSCRIPTION_KEY=${{ parameters.subscriptionKey }} -DTEST_URL=https://${{ parameters.apimHost }} -DTEST_HOST=${{ parameters.apimHost }}

    # - template: ../steps/run-gradlew.yaml
    #   parameters:
    #     runCommand: ${{ parameters.command }} -DTEST_SUBSCRIPTION_KEY=${{ parameters.subscriptionKey }} -DTEST_URL=https://${{ parameters.apimHost }} -DTEST_HOST=${{ parameters.apimHost }}
