parameters:
  - name: displayName
    type: string

  - name: dependsOn
    type: object

  - name: subscription
    type: string

  - name: resourceGroup
    type: string

  - name: storageAccount
    type: string

  - name: storageContainer
    type: string

  - name: subscriptionKey
    type: string

  - name: command
    type: string

  - name: logLevel
    type: string

  - name: variables
    type: object
  
  - name: pactBrokerUrl
    type: string
  
  - name: pool
    type: string

jobs:
- job: ${{ parameters.displayName }}
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    name: ${{ parameters.pool }}
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - bash: |
      wget https://download.java.net/java/ga/jdk11/openjdk-11_linux-x64_bin.tar.gz -O /azp/openjdk-11_linux-x64_bin.tar.gz
  - task: JavaToolInstaller@0
    displayName: 'Use Java 11'
    inputs:
      versionSpec: 11
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: '/azp/openjdk-11_linux-x64_bin.tar.gz'
      jdkDestinationDirectory: jdk
  - ${{ if contains(parameters.command, 'contract') }}:
    - template: ../steps/run-gradlew.yaml
      parameters:
        command: ${{ parameters.command }} -DENDPOINT_SUBSCRIPTION_KEY=$(subscriptionKey)
    - template: ../steps/run-gradlew.yaml
      parameters:
        command: pactPublish -DPACT_BROKER_FULL_URL=${{ parameters.pactBrokerUrl }}
  - template: ../steps/run-gradlew.yaml
    parameters:
      command: ${{ parameters.command }} -DENDPOINT_SUBSCRIPTION_KEY=$(subscriptionKey) -DENDPOINT_URL=https://${{ parameters.apimHost }} -DENDPOINT_HOST=${{ parameters.apimHost }} -DMOCK_SERVER_HOST=localhost -DMOCK_SERVER_PORT=80 -DAPI_LOG_LEVEL=${{ parameters.logLevel }}
  - ${{ if contains(parameters.command, 'functional') }}:
    - template: ../steps/zip-test-results.yaml
      parameters:
        zipName: ${{ parameters.displayName }}_serenity
        directory: /target/site/serenity
  - ${{ if contains(parameters.command, 'test') }}:
    - template: ../steps/zip-test-results.yaml
      parameters:
        zipName: ${{ parameters.displayName }}_unittests
        directory: /build/reports/unittests
  - template: ../steps/zip-test-results.yaml
    parameters:
      zipName: ${{ parameters.displayName }}_gradle
      directory: /build/reports/tests/${{ parameters.command }}
  - template: ../steps/publish-test-results.yaml
    parameters:
      zipName: ${{ parameters.displayName }}
      subscription: ${{ parameters.subscription }}
      resourceGroup: $(resourceGroup)
      storageAccount: $(storageAccount)
      storageContainer: $(storageContainer)
