parameters:
  - name: displayName
    type: string

  - name: dependsOn
    type: object
  
  - name: serenity
    type: string

  - name: subscription
    type: string

  - name: storageAccount
    type: string

  - name: subscriptionKey
    type: string

  - name: apimHost
    type: string

  - name: command
    type: string

  - name: variables
    type: object

jobs:
- job: ${{ parameters.displayName }}
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - template: ../steps/run-gradlew.yaml
    parameters:
      command: ${{ parameters.command }} -DENDPOINT_SUBSCRIPTION_KEY=$(subscriptionKey) -DENDPOINT_URL=https://${{ parameters.apimHost }} -DENDPOINT_HOST=${{ parameters.apimHost }}
  - ${{ if contains(parameters.serenity, true) }}:
    - template: ../steps/zip-test-results.yaml
      parameters:
        command: ${{ parameters.command }}
    - templates: ../publish-test-results.yaml
      parameters:
        command: ${{ parameters.command }}
        subscription: ${{ parameters.subscription }}
        storageAccount: $(storageAccount)
        storageContainer: $(storageContainer)