parameters:
  - name: displayName
    type: string

  - name: dependsOn
    type: object

  - name: subscription
    type: string

  - name: registry
    type: string

  - name: repository
    type: string

  - name: dockerfile
    type: string

  - name: tags
    type: string

  - name: hostVolume
    type: string

  - name: containerVolume
    type: string

  - name: envVars
    type: object

jobs:
- job: ${{ parameters.displayName }}
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ../steps/push-img.yaml
    parameters:
      registry: ${{ parameters.registry }}
      repository: ${{ parameters.repository }}
      dockerfile: ${{ parameters.dockerfile }}
      tags: ${{ parameters.tags }}
  - template: ../steps/run_owasp_api_scan.yaml
    parameters:
      registry: ${{ parameters.registry }}
      repository: ${{ parameters.repository }}
      tags: ${{ parameters.tags }}
      volumes: ${{ parameters.hostVolume }}:${{ parameters.containerVolume }}
      envVars: ${{ parameters.envVars }}
  - template: ../steps/zip-test-results.yaml
    parameters:
      zipName: ${{ parameters.displayName }}
      directory: ${{ parameters.hostVolume }}

  # - template: ../publish-test-results.yaml