parameters:
  - name: displayName
    type: string
  - name: dependsOn
    type: object
  - name: command
    type: string
  - name: subscription 
    type: string
    

jobs:
- job: ${{ parameters.displayName }}
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}

  pool:
    vmImage: 'ubuntu-18.04'
  
  steps:
  - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarCloud: SonarCloud
      organization: hmcts
      scannerMode: Other

  - template: ../steps/run-gradlew.yaml
    parameters:
      command: ${{ parameters.command }} --stacktrace -$(Psonar.login)
      sonarAnalysis: true
      publishJUnitResults: false
  
  - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'
