parameters:
  - name: subscription
    type: string

  - name: group
    type: string

  - name: displayName
    type: string

  - name: dependsOn
    type: string
    default: ''

  - name: shared_infra_kv
    type: string
  
  - name: shared_infra_rg
    type: string

jobs:
- job: Terraform
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  variables:
  - group: ${{ parameters.group }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ../steps/tf-install.yaml
  - template: ../steps/tf-test.yaml
  - template: ../steps/tf-init.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
  - template: ../steps/tf-plan.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
      shared_infra_kv: ${{ parameters.shared_infra_kv }}
      shared_infra_rg: ${{ parameters.shared_infra_rg }}
  - template: ../steps/tf-apply.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
  - template: ../steps/tf-output.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
