parameters:
  - name: subscription
    type: string

  - name: group
    type: string

  - name: displayName
    type: string

  - name: dependsOn
    type: string
    default: ''

jobs:
- job: Terraform
  variables:
  - group: ${{ parameters.group }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - download: current
    displayName: 'Download artifacts'
    artifact: drop
  - download: current
    displayName: 'Download tfplan'
    artifact: $(environment)-hmi.tfvars
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Pipeline.Workspace)/tfplan-$(environment)'
      targetFolder: '$(Pipeline.Workspace)/drop/infrastructure/terraform/'
  - template: ../steps/tf-install.yaml
  - template: ../steps/tf-init.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
  - template: ../steps/tf-output.yaml
    parameters:
      subscription: ${{ parameters.subscription }}