
jobs:
- job: Terraform Validation
  displayName: "Validate Terraform"
  steps:
    - template: templates\tests\terraform\allTests.yaml@azTemplates
      terraformPath: $(System.DefaultWorkingDirectory)/infrastructure/terraform
