
jobs:
- job: TerraformValidation
  displayName: "Validate Terraform"
  steps:
    - template: templates\tests\terraform\allTests.yaml@azTemplates
      parameters:
        terraformPath: $(System.DefaultWorkingDirectory)/infrastructure/terraform
    - powershell: |
        echo "branch $(Build.SourceBranch)"
