parameters:
  - name: subscription
    type: string

  - name: group
    type: string

  - name: displayName
    type: string

jobs:
- job: TerraformPlan
  variables:
  - group: ${{ parameters.group }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ../steps/tf-install.yaml
  - template: ../steps/tf-init.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
  - template: ../steps/tf-plan.yaml
    parameters:
      subscription: ${{ parameters.subscription }}
