parameters:
  - name: displayName
    type: string

  - name: dependsOn
    type: object
    default: ''

  - name: storageContainer
    type: string

  - name: variables
    type: object

  - name: subscriptionKey
    type: string

  - name: subscription
    type: string

jobs:
- job: SmokeTest
  continueOnError: true
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - template: ../steps/download-test-file.yaml
    parameters:
      fileName: smoke
      fileExtension: yaml
      filePath: /src/smokeTest/resources/
  - template: ../steps/run-gradlew.yaml
    parameters:
      command: clean smoke -DENDPOINT_SUBSCRIPTION_KEY=$(subscriptionKey) -DENDPOINT_URL=https://$(hostName) -DENDPOINT_HOST=$(hostName) -DAPI_LOG_LEVEL=DEBUG
  - template: ../steps/zip-test-results.yaml
    parameters:
      zipName: test_smoke
      directory: /build/reports/tests/smoke
  - template: ../steps/publish-test-results.yaml
    parameters:
      zipName: smoke_tests
      subscription: ${{ parameters.subscription }}
      resourceGroup: $(devopsResourceGroup)
      storageAccount: $(devopsStorageAccount)
      storageContainer: $(storageContainer)
