parameters:
  - name: displayName
    type: string

  - name: dependsOn
    type: object
    default: ''

  - name: storageContainer
    type: string
  
  - name: variables
    type: object

jobs:
- job: UnitTest
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  steps:
  - template: ../steps/run-gradlew.yaml
    parameters:
      command: clean test -DENDPOINT_SUBSCRIPTION_KEY=$(subscriptionKey) -DENDPOINT_URL=https://$(apimHost) -DENDPOINT_HOST=$(apimHost)
  - template: ../steps/zip-test-results.yaml
    parameters:
      zipName: test_unittests
      directory: /build/reports/unittests
  - template: ../steps/zip-test-results.yaml
    parameters:
      zipName: test_gradle
      directory: /build/reports/tests/test
  - template: ../steps/publish-test-results.yaml
    parameters:
      zipName: unit_tests
      subscription: $(subscription)
      resourceGroup: $(resourceGroup)
      storageAccount: $(storageAccount)
      storageContainer: $(storageContainer)
