parameters:
  - name: displayName
    type: string

  - name: dependsOn
    type: object
    default: ''

jobs:
- job: CodeQualityTest
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  steps:
  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarCloud: SonarCloud
      organization: hmcts
      scannerMode: Other
      extraProperties: |
        sonar.exclusions=**/*-policy.xml

  - template: ../steps/run-gradlew.yaml
    parameters:
      command: clean sonarqube --stacktrace
      sonarAnalysis: true
      publishJUnitResults: false
  
  - task: SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'
