parameters:
  - name: displayName
    type: string
  - name: dependsOn
    type: object
    default: ''
  - name: environment
    type: string

jobs:
- job: PerformanceTest
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  displayName: ${{ parameters.displayName }}
  steps:
  - checkout: fh-hmi-performance
  - script: dir $(Build.SourcesDirectory)