jobs:
- job: UpdateAgent
  displayName: ${{ parameters.displayName }}
  steps:
  - bash: |
      wget https://download.java.net/java/ga/jdk11/openjdk-11_linux-x64_bin.tar.gz -O /azp/openjdk-11_linux-x64_bin.tar.gz
  - task: JavaToolInstaller@0
    displayName: 'Use Java 11'
    inputs:
      versionSpec: 11
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: '/azp/openjdk-11_linux-x64_bin.tar.gz'
      jdkDestinationDirectory: jdk
  - bash: echo $JAVA_HOME_11_X64