parameters:
  - name: dependsOn
    type: object
    default: ''
  
  - name: subscriptionName
    type: string
  - name: environment
    type: string
  - name: apis
    type: object
    default: []

jobs:
- job: UpdateApimApi
  displayName: Update APIM APIs
  dependsOn:
  - ${{ if parameters.dependsOn }}:
    - ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - ${{ each api in parameters.apis }}:
    - template: templates\Azure\ApiManagement\update-apim-api.yaml@azTemplates
      parameters:
        subscriptionName: ${{ parameters.subscriptionName }}
        apimRgName: "hmi-apim-${{ parameters.environment }}-rg"
        apimName: "hmi-apim-svc-${{ parameters.environment }}"
        apiName: ${{ api.name }}
        format: ${{ api.format }}
        specUrl: ${{ api.specUrl }}
