apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicas }}
  servicename: {{ .Chart.Name }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: ARM_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: vsts-agent-az-client-id
                key: clientId
          - name: ARM_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: vsts-agent-az-client-secret
                key: clientSecret
          - name: ARM_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                name: vsts-agent-az-subscription-id
                key: subscriptionID
          - name: ARM_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: vsts-agent-az-tenant-id
                key: tenantID
         {{- with .Values }}
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: vsts-agent-secret
                key: azpToken
          - name: AZP_URL
            value: {{ .vstsAccount | default "https://dev.azure.com/hmcts/Shared%20Services" }}
          - name: AZP_POOL
            value: {{ .vstsPool | default "hmi-pool" }}
          - name: AZP_WORK
            value: {{ .vstsWorkspace | default "_work" }}
    