parameters:
  - name: environment
    type: string
  - name: subscription
    type: string
  - name: deploymentType
    type: string
    default: 'infra'
  - name: dependsOn
    type: string
    default: ''

stages:
  - stage: Build${{ parameters.environment }}
    displayName: "${{ parameters.environment }} Build"
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: ${{ parameters.dependsOn }}
    variables:
      - group: HMI-APIM-BUILD-${{ parameters.environment }}
      - template: ../variables/${{ parameters.environment }}.yaml
      - template: ../variables/shared.yaml
    jobs:
    - ${{ if eq(parameters.deploymentType, 'infra') }}:
      - template: ../jobs/terraform-apply.yaml
        parameters:
          displayName: Build ${{ parameters.environment }}
          subscription: ${{ parameters.subscription }}
      - template: ../jobs/create-storage-rota.yaml
        parameters:
          displayName: Create ROTA Storage
          subscription: ${{ parameters.subscription }}
          dependsOn: TerraformApply
          environmentName: ${{ variables.env_longname }}
      - template: ../jobs/create-logicapp-dtu.yaml
        parameters:
          displayName: Create DTU Logic Application
          subscription: ${{ parameters.subscription }}
          environment: ${{ parameters.environment }}
          dependsOn: createRotaStorage
          logicApps:
            - name: "hmi-la-rota-dtu",
              path: '$(System.DefaultWorkingDirectory)\infrastructure\logic-app\rota\hmi-la-rota-dtu-la.json' 
            - name: "hmi-la-sittingpattern-publisher",
              path: '$(System.DefaultWorkingDirectory)\infrastructure\logic-app\sitting-pattern\hmi-la-sittingpattern-publisher-la.json'
            - name: "hmi-la-sittingpattern-retriever",
              path: '$(System.DefaultWorkingDirectory)\infrastructure\logic-app\sitting-pattern\hmi-la-sittingpattern-retriever-la.json'

    - ${{ if eq(parameters.deploymentType, 'app') }}:
      - template: ../jobs/update-apim-api.yaml
        parameters:
          subscriptionName: ${{ parameters.subscription }}
          environment: ${{ parameters.environment }}
          apis: 
            - name: hmi-apim-api
              format: Swagger
              specUrl: ${{ variables.api_spec }}
            - name: hmi-apim-api-health
              format: Swagger
              specUrl: ${{ variables.health_api_spec }}
      - template: ../jobs/apply-policies.yaml
        parameters:
          displayName: Apply API Policies
          subscription: ${{ parameters.subscription }}
          environment: ${{ parameters.environment }}
          dependsOn: UpdateApimApi
      - template: ../jobs/remove-default-apis.yaml
        parameters:
          displayName: Remove default APIS
          subscription: ${{ parameters.subscription }}