parameters:
  - name: environment
    type: string
  - name: subscription
    type: string
  - name: dependsOn
    type: string
    default: ''


stages:
  - stage: Plan${{ parameters.environment }}
    displayName: "${{ parameters.environment }} Plan"
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: ${{ parameters.dependsOn }}
    variables:
      - group: HMI-APIM-BUILD-${{ parameters.environment}}
    jobs:
    - template: ../jobs/terraform-plan.yaml
      parameters:
        displayName: TF Plan ${{ parameters.environment }}
        subscription: ${{ parameters.subscription }}