parameters:
  - name: environment
    type: string
  - name: subscription
    type: string
  - name: dependsOn
    type: string
    default: ''


stages:
  - stage: Plan${{ parameters.environment }}
    displayName: "${{ parameters.environment }} Plan"
    pool:
      vmImage: 'ubuntu-latest'
    ${{ if ne(parameters.dependsOn, '') }}:
      dependsOn: ${{ parameters.dependsOn }}
    ${{ elseif eq(parameters.environment, 'prod') }}:
      dependsOn: Teststg
    ${{ else }}:
      dependsOn: Validate
    variables:
      - group: HMI-APIM-BUILD-${{ parameters.environment}}
    jobs:
    - template: ../jobs/terraform-plan.yaml
      parameters:
        displayName: TF Plan ${{ parameters.environment }}
        subscription: ${{ parameters.subscription }}