parameters:
  - name: environment
    type: string
  - name: subscription
    type: string


stages:
  - stage: Test${{ parameters.environment }}
    displayName: "${{ parameters.environment }} Test"
    dependsOn: Build${{ parameters.environment }}
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
      - group: HMI-APIM-BUILD-${{ parameters.environment }}
    jobs:
      - template: pipeline/jobs/create-storage.yaml
        parameters:
          displayName: Create Storage for Test Results
          subscription: ${{ parameters.subscription }}
      
      - template: pipeline/jobs/export-keyvault.yaml
        parameters:
          displayName: Read APIM Subscription Key
          subscription: ${{ parameters.subscription }}

      - template: pipeline/jobs/test-unit.yaml
        parameters:
          displayName: Unit Test
          dependsOn:
          - CreateStorage
          - ExportKeyVault
          subscription: ${{ parameters.subscription }}
          subscriptionKey: $(subscriptionKey)
          storageContainer: $(storageContainer)
          variables:
            storageContainer: $[dependencies.CreateStorage.outputs['createContainer.container']]
            subscriptionKey: $[dependencies.ExportKeyVault.outputs['exportKeyVaultSecret.hmi-apim-sub-key']]

      - template: pipeline/jobs/test-acceptance.yaml
        parameters:
          displayName: Acceptance Test
          dependsOn:
          - CreateStorage
          - ExportKeyVault
          subscription: ${{ parameters.subscription }}
          subscriptionKey: $(subscriptionKey)
          storageContainer: $(storageContainer)
          variables:
            storageContainer: $[dependencies.CreateStorage.outputs['createContainer.container']]
            subscriptionKey: $[dependencies.ExportKeyVault.outputs['exportKeyVaultSecret.hmi-apim-sub-key']]

      - ${{ if or(eq(environment, 'sbox'),eq(environment, 'test'),eq(environment, 'stg')) }}:
        - template: pipeline/jobs/test-codequality.yaml
          parameters:
            displayName: Code Quality Test
            dependsOn:
            - AcceptanceTest

      - ${{ if or(eq(environment, 'test'),eq(environment, 'stg')) }}:
        - template: pipeline/jobs/test-smoke.yaml
          parameters:
            displayName: Smoke Test
            dependsOn:
            - CreateStorage
            - ExportKeyVault
            subscription: ${{ parameters.subscription }}
            subscriptionKey: $(subscriptionKey)
            storageContainer: $(storageContainer)
            variables:
              storageContainer: $[dependencies.CreateStorage.outputs['createContainer.container']]
              subscriptionKey: $[dependencies.ExportKeyVault.outputs['exportKeyVaultSecret.hmi-apim-sub-key']]

      - ${{ if or(eq(environment, 'test'),eq(environment, 'stg')) }}:
        - template: pipeline/jobs/test-functional.yaml
          parameters:
            displayName: Functional Test
            dependsOn:
            - CreateStorage
            - ExportKeyVault
            subscription: ${{ parameters.subscription }}
            subscriptionKey: $(subscriptionKey)
            storageContainer: $(storageContainer)
            variables:
              storageContainer: $[dependencies.CreateStorage.outputs['createContainer.container']]
              subscriptionKey: $[dependencies.ExportKeyVault.outputs['exportKeyVaultSecret.hmi-apim-sub-key']]
