parameters:
  - name: dependsOn
    type: string
    default: ''
  - name: condition
    type: string
    default: 'always()'
  - name: deploymentType
    type: string
    default: 'infra'

stages:
  - stage: Validate
    ${{ if eq(parameters.dependsOn, '') }}:
      dependsOn: []
    ${{ if ne(parameters.dependsOn, '') }}:
      dependsOn: '${{parameters.dependsOn}}'
    condition: ${{ parameters.condition }}
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - ${{ if eq(parameters.deploymentType, 'infra') }}:
        - template: ../jobs/terraform-validate.yaml
      - ${{ if eq(parameters.deploymentType, 'app') }}:
        - template: ../jobs/test-polices.yaml