parameters:
  - name: environment
    type: object
    default: []

stages:
  - stage: ${{ parameters.stageName }}
    ${{ if ne(parameters.condition, '') }}:
      condition: ${{ parameters.condition }}
    dependsOn:
    - ${{ if parameters.dependantStages }}:
      - ${{ parameters.dependantStages }}