targetInstance: ${TEST_URL:https://hmi-apim-svc-sbox.azure-api.net}
targetHost : ${TEST_HOST:hmi-apim-svc-sbox.azure-api.net}
targetSubscriptionKey : ${TEST_SUBSCRIPTION_KEY:1ab2985afb424aed9d38b92c38bacc0f}
spring.flyway.enabled: false
