targetInstance: ${TEST_URL:https://hmi-apim-svc-test.azure-api.net}
targetHost : ${TEST_HOST:hmi-apim-svc-test.azure-api.net}
targetSubscriptionKey : ${TEST_SUBSCRIPTION_KEY:587c56f59a604054b1ce73dac0ea5b28}
spring.flyway.enabled: false
