---
trigger:
  - none

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: 'sbox'
    values:
      - sbox

variables:
  - group: HMI-APIM-Common
  - ${{ if eq(parameters.environment, 'sbox') }}:
    - group: HMI-APIM-BUILD-SBOX
  - ${{ if eq(parameters.environment, 'test') }}:
    - group: HMI-APIM-BUILD-TEST

resources:
  containers:
  - container: wiremock_container
    image: hmi/apim-tests-wiremock:latest
    endpoint: 'DTS-SS-ACRPrivate'
    options: --user 0:0
    ports:
    - 8080:8080

stages:

  - stage: TEST
    displayName: Create ACR Images
    jobs:
      - job: BuildACRimage
        pool:
          vmImage: 'ubuntu-latest'

        steps:
        - template: pipeline/steps/push-img.yaml
          parameters:
            registry: 'DTS-SS-ACRPrivate'
            repository: 'hmi/apim-tests-wiremock'
            dockerfile: 'pipeline/tests/wiremock/Dockerfile'
            tags: |
              latest

  - stage: WIREMOCK
    displayName: Tests - Wiremock
    jobs:
      - job: containerjob
        pool:
          vmImage: 'ubuntu-16.04'
        services: 
          wiremock: wiremock_container
        steps:
        - script: curl http://localhost:8080/product/p0001