---
trigger:
  - master
pr:
  - none

parameters:
  - name: environments
    type: object
    default:
    - name: sbox
      subscription: DTS-SHAREDSERVICES-SBOX
    
    - name: dev
      subscription: DTS-SHAREDSERVICES-DEV


jobs:
- ${{ each environment in parameters.environments }}:
  - job:
    displayName: Build and Test ${{ environment.name }} APIM
    steps:
    - bash: |
        echo ${{ environment.name }}