---
trigger:
  - master
pr:
  - none

parameters:
  - name: environments
    type: object
    default:
    - name: sbox
      subscription: DTS-SHAREDSERVICES-SBOX
    
    - name: dev
      subscription: DTS-SHAREDSERVICES-DEV

stages:

- ${{ each environment in parameters.environments }}:

  - stage: ${{ environment.name }}
    displayName: Build and Test ${{ environment.name }} APIM

    jobs:
    - job:
      steps:
        - task:
          script: |
            echo ${{ environment.name }}