targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hmiApiRootContext : /hmi/
hearingsApiRootContext: /hmi/hearings
hearings_idRootContext: /hmi/hearings/%s
schedulesApiRootContext: /hmi/schedules
resourcesRootContext: /hmi/resources
resourcesByLocation_idRootContext: /hmi/resources/location/%s
resources_idRootContext: /hmi/resources/%s
resourcesByUser_idRootContext: /hmi/resources/user/%s
sessionsRootContext: /hmi/sessions
sessions_idRootContext: /hmi/sessions/%s
listingsRootContext: /hmi/listings
spring.flyway.enabled: false

mockServerHost: ${MOCK_SERVER_HOST}
mockServerPort: ${MOCK_SERVER_PORT}
