targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hmiApiRootContext : /hmi/
hearingApiRootContext: /hmi/hearings
updateHearingRootContext: /hmi/hearings/%s
retrieveIndividualHearingRootContext: /hmi/hearings/%s
sessionApiRootContext: /hmi/sessions
spring.flyway.enabled: false

mockServerHost: ${MOCK_SERVER_HOST}
mockServerPort: ${MOCK_SERVER_PORT}
