targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hmiApiRootContext : /hmi/
hearingApiRootContext: /hmi/hearings
updateHearingRootContext: /hmi/hearings/%s
sessionApiRootContext: /hmi/sessions
resourcesRootContext: /hmi/resources
resources_idRootContext: /hmi/resources/%s

spring.flyway.enabled: false

mockServerHost: ${MOCK_SERVER_HOST}
mockServerPort: ${MOCK_SERVER_PORT}
