targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hmiApiRootContext : /hmi/
hearingsApiRootContext: /hmi/hearings
hearings_idRootContext: /hmi/hearings/%s
schedulesApiRootContext: /hmi/schedules
resourcesRootContext: /hmi/resources
resourcesByLocationRootContext: /hmi/resources/location/
resourcesByLocation_idRootContext: /hmi/resources/location/%s
resources_idRootContext: /hmi/resources/%s
resourcesByUserRootContext: /hmi/resources/user/
resourcesByUser_idRootContext: /hmi/resources/user/%s
sessionsRootContext: /hmi/sessions
sessions_idRootContext: /hmi/sessions/%s
listingsRootContext: /hmi/listings
listings_idRootContext: /hmi/listings/%s

grantType: client_credentials
clientID: b085c529-1b29-4075-969c-32ebfaddb1e4
clientSecret: 4b3eca29-2ff6-4419-8061-2b23cef9e756
token_apiTenantId: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
token_apiURL: https://login.microsoftonline.com/%s/oauth2/v2.0/token
scope: api://d49d7fa2-6904-4223-a907-3b8992af4190/.default

spring.flyway.enabled: false

mockServerHost: ${MOCK_SERVER_HOST}
mockServerPort: ${MOCK_SERVER_PORT}
