targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hmiApiRootContext : /hmi/
hearingsApiRootContext: /hmi/hearings
hearings_idRootContext: /hmi/hearings/%s
schedulesApiRootContext: /hmi/schedules
resourcesRootContext: /hmi/resources
resourcesByLocation_idRootContext: /hmi/resources/location/%s
resources_idRootContext: /hmi/resources/%s
resourcesByUser_idRootContext: /hmi/resources/user/%s
sessionsRootContext: /hmi/sessions
sessions_idRootContext: /hmi/sessions/%s
listingsRootContext: /hmi/listings
listings_idRootContext: /hmi/listings/%s

grantType: client_credentials
clientID: 49e9c094-4267-4137-828e-06626fb6fec1
clientSecret: 0254e211-e6a7-49c1-8957-e35428245ef3
token_apiTenantId : 4cdea387-4a31-46b1-b99a-c9e41aa989a3
token_apiURL : https://login.microsoftonline.com/%s/oauth2/v2.0/token
scope: api://9b6e8260-abef-4874-8978-ef4b4058edf8/.default

spring.flyway.enabled: false

mockServerHost: ${MOCK_SERVER_HOST}
mockServerPort: ${MOCK_SERVER_PORT}
