targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hearingsApiRootContext: /hmi/hearings
hmiApiRootContext : /hmi/
schedulesApiRootContext: /hmi/schedules
notificationApiRootContext : /notification
resourcesApiRootContext : /hmi/resources
sessionsApiRootContext: /hmi/sessions
userApiRootContext : /users
spring.flyway.enabled: false
