targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hearingsApiRootContext: /hmi/hearings
hmiApiRootContext : /hmi/
schedulesApiRootContext: /hmi/schedules
notificationApiRootContext : /notification
resourcesApiRootContext : /hmi/resources
sessionsApiRootContext: /hmi/sessions
listingsApiRootContext: /hmi/listings
userApiRootContext : /users
spring.flyway.enabled: false

grantType: client_credentials
clientID: b085c529-1b29-4075-969c-32ebfaddb1e4
clientSecret: 4b3eca29-2ff6-4419-8061-2b23cef9e756
token_apiTenantId: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
token_apiURL: https://login.microsoftonline.com/%s/oauth2/v2.0/token
scope: api://d49d7fa2-6904-4223-a907-3b8992af4190/.default
