targetInstance: ${ENDPOINT_URL}
targetHost: ${ENDPOINT_HOST}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hearingApiRootContext: /hmi/hearings
hmiApiRootContext : /hmi/
sessionApiRootContext : /sessions
notificationApiRootContext : /notification
userApiRootContext : /users
spring.flyway.enabled: false
