targetInstance: ${TEST_URL:https://hmi-apim-svc-test.azure-api.net}
targetHost : ${TEST_HOST:hmi-apim-svc-test.azure-api.net}
targetSubscriptionKey : ${TEST_SUBSCRIPTION_KEY:xxx}
hearingApiRootContext: /hmi-apim-api/hearings
hmiApiRootContext : /hmi-apim-api/
spring.flyway.enabled: false
