targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hearingApiRootContext: /hmi/hearings
hmiApiRootContext : /hmi/
sessionApiRootContext : /schedules
notificationApiRootContext : /notification
userApiRootContext : /users
spring.flyway.enabled: false
