targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}
hearingApiRootContext: /hmi/hearings
hmiApiRootContext : /hmi/
sessionApiRootContext : /sessions
notificationApiRootContext : /notification
userApiRootContext : /users
resourcesAPIRootContext : /hmi/resources
spring.flyway.enabled: false
