targetInstance: ${ENDPOINT_URL}
targetSubscriptionKey: ${ENDPOINT_SUBSCRIPTION_KEY}

hmiApiRootContext : /casehqapi/rest/hmcts/
hearingsApiRootContext: /casehqapi/rest/hmcts/resources/hearings
sessionsApiRootContext: /casehqapi/rest/hmcts/resources/sessions
#hearings_idRootContext: /hmi/hearings/%s
#schedulesApiRootContext: /hmi/schedules
#resourcesRootContext: /hmi/resources
#resourcesByLocationRootContext: /hmi/resources/location/
#resourcesByLocation_idRootContext: /hmi/resources/location/%s
#resources_idRootContext: /hmi/resources/%s
#resourcesByUserRootContext: /hmi/resources/user/
#resourcesByUser_idRootContext: /hmi/resources/user/%s
#sessionsRootContext: /hmi/sessions
#sessions_idRootContext: /hmi/sessions/%s
#listingsRootContext: /hmi/listings
#listings_idRootContext: /hmi/listings/%s

#grantType: client_credentials
#clientID: b085c529-1b29-4075-969c-32ebfaddb1e4
#clientSecret: 4b3eca29-2ff6-4419-8061-2b23cef9e756
#token_apiTenantId: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
#token_apiURL: https://login.microsoftonline.com/%s/oauth2/v2.0/token
#scope: api://d49d7fa2-6904-4223-a907-3b8992af4190/.default

token_apiURL: https://hmcts-uat.casehq.net/hmi_oauth2/resources/hmi/token
token_username: ${TOKEN_USERNAME}
token_password: ${TOKEN_PASSWORD}

expired_access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOiJhcGk6Ly9iZTZmODQ1NC1hNTg0LTQxZjctYmQ3NC1lYTZjNDAzMmMzYTQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC80Y2RlYTM4Ny00YTMxLTQ2YjEtYjk5YS1jOWU0MWFhOTg5YTMvIiwiaWF0IjoxNjAzMTAxNjMyLCJuYmYiOjE2MDMxMDE2MzIsImV4cCI6MTYwMzEwNTUzMiwiYWlvIjoiRTJSZ1lQQTl4MUZ5WWIreENvUDRxdWNabGFwYkFRPT0iLCJhcHBpZCI6Ijk5MTJmMDVlLTIxZjYtNGE2YS05Y2ExLWRiMTAxMzA2ZGI0NSIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzRjZGVhMzg3LTRhMzEtNDZiMS1iOTlhLWM5ZTQxYWE5ODlhMy8iLCJvaWQiOiIwNmU4YWJjOS1jNWI5LTQ2ODctOWU3Yi01ZTA4NzhmMGQzZjkiLCJyaCI6IjAuQUFBQWg2UGVUREZLc1VhNW1zbmtHcW1KbzE3d0VwbjJJV3BLbktIYkVCTUcyMFZoQUFBLiIsInJvbGVzIjpbImhtaUdhdGV3YXkiXSwic3ViIjoiMDZlOGFiYzktYzViOS00Njg3LTllN2ItNWUwODc4ZjBkM2Y5IiwidGlkIjoiNGNkZWEzODctNGEzMS00NmIxLWI5OWEtYzllNDFhYTk4OWEzIiwidXRpIjoiN0hidUw3RW5DVS16RElzcGxGaUZBQSIsInZlciI6IjEuMCJ9.poHTnormTDTpRtA5LtM4iBiFcJd0c2EyTtWD_zVZddHqZO9U_zN-2FTYX-P7AXd9ky7WlWcDoW7nGinIJbv5CUOp5doPNSJJVqEeUrtXkQclV0wG1csWsjF_OTQSD_gGyZQtrSuBQLYVBKhF-actgJQaAtnwNiSnF7XSFld_W4xMC7PmNir3Rz2GLBrKWCZhKt3kewK3Fc-vPwiGXGfYF5hbcIiWVoIq62tAD_w44OJPs_2PC8eAnifFjBapjFgGVFbLYTxah3tMGhlsiEEXJK7c0HR1LQOSYj0tPh7lzP64aXy9VJewlfJTKWodOsh7rI96YByUt55bIupK1tcJ-g

spring.flyway.enabled: false

mockServerHost: ${MOCK_SERVER_HOST}
mockServerPort: ${MOCK_SERVER_PORT}
