# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - fh-hmi-api-prototype

variables:
  terraformVersion: 0.12.9

stages:
  - stage: ci_config_check
    displayName: CI - Config Check
    jobs:
    - template: pipeline/steps/01-config-check.yml
      parameters:
        terraformVersion: ${{ variables.terraformVersion }}
  
  - stage: create_artifacts
    displayName: CI - Create Artifact
    dependsOn: ci_config_check
    condition: succeeded('ci_config_check')
    jobs:
    - template: pipeline/steps/02-create-artifact.yml