prefix = "hmi-apim"
environment = "sbox"
location = "uksouth"
sku_name = "Delevoper_1"
open_api_spec_content_format = "swagger-link-json"
open_api_spec_content_value = "https://raw.githubusercontent.com/hmcts/reform-api-docs/master/docs/specs/future-hearings-request-hearing.json"
service_url = "https://www.hmcts.com/request-hearings/request-listings"